language: objective-c
xcode_workspace: Example/Example.xcworkspace
xcode_scheme: Example
xcode_sdk: iphonesimulator
xcode_simulator: ipad

before_install:
  - "brew unlink xctool"
  - "brew install xctool --HEAD"
  - "brew link xctool"